name: convert_case
description: Easily convert case of strings
version: 0.9.1
repository: https://github.com/YarostheLaunchpadder/convert_case
issue_tracker: https://github.com/YarostheLaunchpadder/convert_case/issues

environment:
  sdk: ">=2.19.2 <3.0.0"

dev_dependencies:
  test: ^1.24.2
  lints: ^2.0.1
